In [14]:
import numpy as np
import pandas as pd

# Numpy and Pandas

Beyond the basic objects, numpy and pandas provide increased functionality to base python.

Numpy is used for faster numerical computation. When large computations are required, numpy speeds things up. If your code is slow, particularly when using large lists, numpy will likely speed things up. Numpy assumes homogeneous type (i.e. all values are float).

Pandas brings dataframes (if you're familiar with R language, these dataframes are similar) to python. Pandas dataframes are basically excel sheets that function as dictionaries. Pandas can read csv and xlsx sheets.

### Numpy

In [53]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
np.zeros(10) - np.ones(10)

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [57]:
np.random.rand(10)

array([0.89915052, 0.75037507, 0.43310658, 0.81727042, 0.82042729,
       0.64008867, 0.25337507, 0.74449566, 0.39802297, 0.55167404])

In [58]:
np.random.rand(10).sum()

5.749915701133508

### Pandas

In [66]:
df = pd.DataFrame()



df['order number'] = np.random.randint(0, 1000, 10)
df['year'] = 2020

df['quantity'] = list(range(10))
df

order number  year  quantity
0           127  2020         0
1           739  2020         1
2           435  2020         2
3           188  2020         3
4           129  2020         4
5           824  2020         5
6           616  2020         6
7           657  2020         7
8           403  2020         8
9             0  2020         9

In [67]:
df['quantity']

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: quantity, dtype: int64